import tkinter as tk
from tkinter import filedialog, messagebox
import subprocess
import os

class VirtualGamerPC:
    def __init__(self, root):
        self.root = root
        self.root.title("Virtual Gamer PC")
        self.root.geometry("600x450")
        self.iso = ""
        self.disk = "GamerPC.qcow2"

        tk.Label(root, text="VIRTUAL GAMER PC",
                 font=("Arial", 24, "bold")).pack(pady=25)

        tk.Label(root, text="PC Virtual Gamer Potente",
                 font=("Arial", 13)).pack(pady=5)

        tk.Button(root, text="Selecionar ISO",
                  command=self.select_iso,
                  width=25).pack(pady=15)

        tk.Button(root, text="Criar Disco Virtual",
                  command=self.create_disk,
                  width=25).pack(pady=15)

        tk.Button(root, text="INICIAR PC VIRTUAL",
                  command=self.start_vm,
                  width=25).pack(pady=15)

        tk.Button(root, text="Sair",
                  command=root.destroy,
                  width=25).pack(pady=15)

        self.status = tk.Label(root, text="Aguardando...",
                               font=("Arial", 11))
        self.status.pack(pady=20)

    def select_iso(self):
        self.iso = filedialog.askopenfilename(
            filetypes=[("Arquivos ISO", "*.iso")]
        )
        if self.iso:
            self.status.config(text="ISO selecionada.")

    def create_disk(self):
        try:
            subprocess.run([
                "qemu-img", "create", "-f",
                "qcow2", self.disk, "80G"
            ], check=True)
            self.status.config(text="Disco virtual criado.")
        except Exception:
            messagebox.showerror("Erro", "QEMU não encontrado.")

    def start_vm(self):
        if not os.path.exists(self.disk):
            messagebox.showwarning("Aviso", "Crie o disco primeiro.")
            return

        command = [
            "qemu-system-x86_64",
            "-name", "VirtualGamerPC",
            "-machine", "q35",
            "-accel", "whpx",
            "-cpu", "host",
            "-smp", "6",
            "-m", "8192",
            "-drive", f"file={self.disk},format=qcow2",
            "-device", "virtio-vga",
            "-device", "virtio-net-pci",
            "-netdev", "user,id=net0"
        ]

        if self.iso:
            command += ["-cdrom", self.iso]

        try:
            subprocess.Popen(command)
            self.status.config(text="PC virtual iniciado!")
        except Exception as error:
            messagebox.showerror("Erro", str(error))

root = tk.Tk()
app = VirtualGamerPC(root)
root.mainloop()
